
name: Github-coPilot Action

on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true

jobs:
  HyperExecute-Playwright:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone https://github.com/gagan-lambda/contosotraders-cloudtesting.git
          echo "STEP 2) Download CLI and setting environment variables"
              cd src/ContosoTraders.Ui.Website
              npm install
              npm run start &
              curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
              chmod u+x hyperexecute
              ./hyperexecute --user ${{ github.event.inputs.username }} --key ${{ github.event.inputs.accessKey }} --download-artifacts  --config hyperexecute-matrix.yaml
